---
apiVersion: policy.open-cluster-management.io/v1
kind: PolicyGenerator
metadata:
  name: gen-policy-clusterclaims
policyDefaults:
  namespace: bry-tam-policies
  remediationAction: enforce
  consolidateManifests: false
  policySets:
    - cluster-configs-clusterclaims
  categories:
    - "CM Configuration Management"
  controls:
    - "CM-2 Baseline Configuration"
  standards:
    - "NIST SP 800-53"
  policyLabels:
    policy_gen.name: clusterclaims
  severity: low

placementBindingDefaults:
  name: "clusterclaims-binding"

policies:
  - name: acm-clusterclaims
    description: "Creates ClusterClaims that expose install-config name and OCP minor version as ManagedCluster labels"
    manifests:
      - path: install-config-name.yml
        name: install-config-name
      - path: minor-version.yml
        name: minor-version

policySets:
  - name: cluster-configs-clusterclaims
    placement:
      placementName: "env-bound-placement"
