---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - apiserver-cert/
  - aro/merge-rh-pull-secret/
  - cluster-autoscaling/
  - clusterclaims/
  - cluster-proxy/
  - default-scheduler/
  - etcd-backup/
  - etcd-encryption/
  - image-registry-s3/
  - image-registry-pvc/
  - ingress/
  - ingress-renew-default-cert/
  - kubeletconfig/
  - machineconfigpools/
  - machinesets/
  - monitoring/
  - nodes/
  - disable-self-provisioner/
  - htpasswd-breakglass/
  - remove-kubeadmin/
