---
apiVersion: policy.open-cluster-management.io/v1beta1
kind: OperatorPolicy
metadata:
  name: nmstate-operator-install
spec:
  complianceType: musthave
  complianceConfig:
    catalogSourceUnhealthy: NonCompliant
    deploymentsUnavailable: NonCompliant
    upgradesAvailable: Compliant
  remediationAction: enforce
  removalBehavior:
    clusterServiceVersions: Delete
    customResourceDefinitions: Delete
    operatorGroups: DeleteIfUnused
    subscriptions: Delete
  severity: critical
  upgradeApproval: Automatic
  subscription:
    channel: stable
    name: kubernetes-nmstate-operator
    namespace: openshift-nmstate
    source: redhat-operators
    sourceNamespace: openshift-marketplace
  operatorGroup:
    name: openshift-nmstate
