---
apiVersion: v1
kind: Secret
metadata:
  name: logicmonitor-credentials
  namespace: logicmonitor
data:
  account: bXktbG9naWNtb25pdG9yLWFjY291bnQ=
  accessID: TE1hMWIyYzNkNGU1ZjZnN2g4
  accessKey: QWIxQ2QyRWYzR2g0SWo1S2w2TW43T3A4UXI5U3QwVXYxV3gyWXoz
