---
apiVersion: k8s.ovn.org/v1
kind: ClusterUserDefinedNetwork
metadata:
  name: example-vlan-200
spec:
  namespaceSelector:
    matchLabels:
      cudn-vmdata-vlan: example-vlan-200
  network:
    topology: Localnet
    localnet:
      ipam:
        mode: Disabled
      mtu: 1500
      physicalNetworkName: localnet-2
      role: Secondary
      vlan:
        mode: Access
        access:
          id: 200
