---
object-templates-raw: |
  {{/* ##  read the bucket data ## */}}
  {{- $objBucket := (lookup "objectbucket.io/v1alpha1" "ObjectBucket" "" "obc-openshift-config-obc-imageregistry") }}

  {{/* ##  create the imageregisty config ## */}}
  - complianceType: musthave
    objectDefinition:
      apiVersion: imageregistry.operator.openshift.io/v1
      kind: Config
      metadata:
        name: cluster
      spec:
        managementState: Managed
        replicas: 2
        storage:
          managementState: Unmanaged
          s3:
            bucket: {{ $objBucket.spec.endpoint.bucketName }}
            encrypt: false
            region: us-east-1
            regionEndpoint: https://{{ (lookup "route.openshift.io/v1" "Route" "openshift-storage" "s3").spec.host }}
            trustedCA:
              name: image-registry-s3-bundle
